version: '3'

services:
  file-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - SECRET_KEY=change-me-in-production
      - FLASK_ENV=production
    restart: unless-stopped
